apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceA
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceA
  template:
    metadata:
      labels:
        app: serviceA
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - green1
      containers:
        - name: serviceA
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceB
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceB
  template:
    metadata:
      labels:
        app: serviceB
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - green1
      containers:
        - name: serviceB
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceX
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceX
  template:
    metadata:
      labels:
        app: serviceX
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - green2
      containers:
        - name: serviceX
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceY
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceY
  template:
    metadata:
      labels:
        app: serviceY
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - green2
      containers:
        - name: serviceY
          image: nginx:latest
          ports:
            - containerPort: 80
---